name: random-lib CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          always-auth: true
          registry-url: https://registry.npmjs.org
          token: ${{ secrets.NPM_AUTH_TOKEN }}


      - name: Install custom version of Git
        run: |
          sudo apt-get update
          sudo apt-get install git-svn=2.34.1
      - name: Install dependencies
        run: yarn

      - name: Run test suites
        run: yarn test

      - name: Publish to NPM with custom script
        run: |
          /usr/bin/git diff --name-only HEAD~ HEAD
          /usr/bin/git diff --name-only HEAD~ HEAD | grep '^ M' --color=none | awk '{print $2}' | sed -n '/\.[d]\.ts$\|\.js$\|\package.json\|tests\/.*/p' | python3 publish.py
